volumes:
  db:
    driver_opts:
      type: tmpfs
      device: tmpfs

networks:
  db:

services:
  db:
    image: mariadb:lts
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
    ports:
      - target: 3306
        published: ${DB_PORT}
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
      MARIADB_DATABASE: ${DB_NAME}
    volumes:
      - db:/var/lib/mysql
    networks:
      - db

  eri:
    depends_on:
      db:
        condition: service_healthy
    build:
      context: .
    environment: # Empty values will passthrough corresponding variables to app
      DB_NAME:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD:
      AUTH_SECRET:
      AUTH_SESSION_COOKIE_NAME:
    command: sh -c "npm exec mikro-orm schema:create -- -r && node --run start"
    ports:
      - "3000:3000"
    networks:
      - db
