volumes:
  db_dev:

networks:
  db:

services:
  eri:
    depends_on:
      db_dev:
        condition: service_healthy

    build: .

    volumes:
      - ../..:/workspaces:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    ports:
      - 3000
    networks:
      - db
  
  db_dev:
    image: mariadb:lts
    restart: unless-stopped
    volumes:
      - db_dev:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: mariadb_dev
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
    ports:
      - "3308:3306"
    networks:
      - db
